language: node_js
node_js:
  - '8.10.0'

script: 
  - cd web-app/
  - npm install
  - npm run build
  - ./node_modules/surge/lib/cli.js --project ./dist/ --domain jsvisualisationemf.obeonetwork.surge.sh
